services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - server